### ISSUE TITLE
add `browser` option to `package.json`

### ISSUE THREAD

**Issue by hanzichi** [LiosK/UUID.js#11]
When it's packed with webpack, the bundle is too large because of the polyfills of the `crypto` module, you can try it with the simple `require('uuidjs')` and webpack it !

So just adding `browser` option to `package.json` can make it used in browser. 

I just simply to offer a PR for you, it's better to extract `cryptoPRNG` function out

https://github.com/LiosK/UUID.js/pull/10

**Comment by LiosK** [comment]
Thank you for your helpful report. Yeah, 300KB+ is obviously too much for a simple UUID library.

I've just inserted a feature toggle that works well with webpack's DefinePlugin so webpack can statically eliminate the `crypto` related lines. Can you please check out `dev` branch and try it out? You can remove `crypto` from your bundle once you append the following code to the `plugins` list in your `webpack.config.js`:

```javascript
new webpack.DefinePlugin({
  'typeof UUIDJS_NO_REQUIRE_CRYPTO': JSON.stringify(typeof true),
}),
```

I'll continue to test this new feature for a while and then release it officially.

**Comment by LiosK** [comment]
I’m not inclined to change the default behavior of the library in v4.x series. That’s why I choose to require an extra step to enable the optimization.

Anyway thank you very much for your suggestion.

**Comment by hanzichi** [comment]
okay, thanks

**Comment by LiosK** [comment]
I have just found a much more elegant way to exclude `crypto` from a webpack bundle, which is just adding the following `browser` field to `package.json`.

```javascript
"browser": {
  "crypto": false
}
```

**Comment by hanzichi** [comment]
it seems to work well, but I am not sure whether it is the right usage, pls check it
