### ISSUE TITLE
TypeScript Declaration File

### ISSUE THREAD

**Issue by bennyn** [LiosK/UUID.js#6]
I would like to use "UUID.js" in a TypeScript project. Unfortunately this project does not have a TypeScript definiton file (`.dts`): https://www.npmjs.com/package/@types/uuidjs

I saw that "UUID.js" is well-documented and uses JSDoc. With JSDoc and [tsd-jsdoc](https://github.com/englercj/tsd-jsdoc) it's possible to auto-generate a `*.d.ts` file.

I can create a Pull Request with the generated definition file (includig "tsd-jsdoc" setup) if you would accept it. 😃

**Comment by bennyn** [comment]
I submitted a Pull Request for this issue: https://github.com/LiosK/UUID.js/pull/7 😃

**Comment by LiosK** [comment]
Added a declaration file under `dev` branch though it's not tested at all yet.

**Comment by LiosK** [comment]
v3.6.0
