### ISSUE TITLE
License violation spotted - another organization stole your project

### ISSUE THREAD

**Issue by HarukaMa** [LiosK/UUID.js#9]
The project, https://github.com/benchlab/KeplerUUID, copied your project without attribution and violated your license by claiming the author.

I've done a diff between the projects which could be found [here](https://pastebin.com/vJ4r97Nf), if you want to take a look at.

I'd suggest you talk to the project directly or report it to GitHub to takedown the violating repository.

**Comment by LiosK** [comment]
Thank you for letting me know.
